#!/bin/sh

global.bootm.image=/sd/zImage
#global.bootm.oftree=/sd/imx25-openx32.dtb
global linux.bootargs.base="console=ttymxc4,115200 root=/dev/mmcblk0p3 rw video=imxfb:800x480 vt.global_cursor_default=0"

